### ISSUE TITLE
Dependency not available on Maven Repo?

### ISSUE THREAD

**Issue by EM-Creations** [gradlex-org/java-module-testing#68]
Hi,

Is something wrong with releases of the library? I've used this previously at work and it was no problem but I'm now trying to use your great library in some personal work and Gradle can't seem to find the depdendency:
`Could not find org.gradlex:java-module-testing:1.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/gradlex/java-module-testing/1.4/java-module-testing-1.4.pom
       - https://dl.google.com/dl/android/maven2/org/gradlex/java-module-testing/1.4/java-module-testing-1.4.pom`

**Comment by jjohannes** [comment]
This looks like something is wrong with your setup.

This Gradle Plugin is only released on plugins.gradle.org.

You most likely miss a "gradlePluginsPortal()" in one of your "repositories" blocks.

**Comment by EM-Creations** [comment]
> This looks like something is wrong with your setup.
> 
> This Gradle Plugin is only released on plugins.gradle.org.
> 
> You most likely miss a "gradlePluginsPortal()" in one of your "repositories" blocks.

Thanks that's probably the problem!
