### ISSUE TITLE
javaModuleTesting.classspath not working

### ISSUE THREAD

**Issue by valodzka** [gradlex-org/java-module-testing#75]
I'm testing 1.5 with this:

`javaModuleTesting.classspath(testing.suites["test"])
`

And it doesn't work:

```
An exception occurred applying plugin request [id: 'buildlogic.java-conventions']
> Failed to apply plugin 'buildlogic.java-conventions'.
   > org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method classspath() for arguments [org.gradle.api.plugins.jvm.internal.DefaultJvmTestSuite_Decorated@53e09c73] on extension 'javaModuleTesting' of type org.gradlex.javamodule.testing.JavaModuleTestingExtension.

```

**Comment by jjohannes** [comment]
Hi. There is a typo in your setup (and the title of this issue 😄 ). Please use:

```
javaModuleTesting.classpath(testing.suites["test"]) 
```

(with two `ss` in the middle and not three `sss`)

In such cases, you can also try your configuration in an example project with Kotlin DSL. Then you should have better code completion and error reporting.

I found that I had the same typo here (now corrects): https://github.com/gradlex-org/java-module-testing/issues/47#issuecomment-2188034115

Apologies, if you copy-pasted from there.
